version: "3"
services:
  api:
    restart: always
    container_name: api
    image: api
    build: api/
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DEBUG: 1
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - backend
    volumes:
      - ./api:/code

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:latest
    command: mongod --port 27017
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
    # environment:
    #   - MONGO_DATA_DIR=/data/db
    volumes:
      - ./mongodata/db_data:/data/db

networks:
  backend:
    external: false
    driver: bridge
volumes:
  mongodata:
