name: Build and Deploy

on:
  release:
    types: [ "created" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Set Docker tags
      run: |
        echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
    - name: Log into GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        context: backend/api
        tags: ghcr.io/DockWizard/backend:${{ env.tag }}
    
    - name: Deploy to K8s
      run: |
        curl -L "https://get.helm.sh/helm-v3.11.2-linux-amd64.tar.gz" -o - | tar xvz
        mv linux-amd64/helm ./helm
        chmod +x ./helm

        echo $KUBECONFIG > /tmp/kubeconfig
        export KUBECONFIG=/tmp/kubeconfig
        ./helm upgrade --install --namespace dockwizard -f deploy/dockwizard-backend/values.yaml dockwizard-backend ./deploy/dockwizard-backend --set image.tag=${{ env.tag }}
